# This workflow will update the installation cache and install Python
# dependencies, run tests with coverage, and lint with Python matrix.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pytest & Coverage

on:
  push:
    branches: ["main", "release-**"]
  pull_request:
    branches: ["main", "release-**"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # no need to run tests for documentation
    if: ${{ !contains(github.event.head_commit.message, 'docs(') &&
      !contains(github.event.head_commit.message, 'docs:') }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
          uv pip install -e .[tests]
      - name: Lint with flake8
        run: |
          # stop if Python syntax errors or undefined names
          uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=".venv,.git,__pycache__,docs"
          # exit-zero treats all errors as warnings
          # This ignores a bunch of linting errors
          uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics --ignore=E226,E231,E265,E501,W291,W293,W503 --exclude=".venv,.git,__pycache__,docs"
      - name: Test with pytest and get coverage
        run: |
          uv run coverage run --rcfile .coveragerc -m pytest && uv runcoverage report
